language: php
dist: trusty
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - exit 0
  - phpunit --coverage-clover clover.xml